"""
Django settings for culture_chatbot project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

from pathlib import Path
import os
from dotenv import load_dotenv
import logging
from decouple import config

# =================================== .env 파일 로드 ===================================
load_dotenv()

logging.basicConfig(level=logging.ERROR)

APPEND_SLASH=False


# =================================== OpenAI API 설정 ===================================
OPENAI_API_KEY = os.getenv('OPENAI_API_KEY')

if not OPENAI_API_KEY:
    raise ValueError("OpenAI API key is missing.")
# =========================================================================================================

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# =================================== SECRET_KEY를 환경 변수에서 읽어오기 ===================================
SECRET_KEY = os.getenv('SECRET_KEY')
if not SECRET_KEY:
    raise ValueError("SECRET_KEY is not set in the .env file")

# =================================== 디버그 모드 설정 ===================================
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


# =================================== ALLOWED_HOSTS 설정 (환경 변수에서 불러오기) ===================================
ALLOWED_HOSTS = os.getenv('DJANGO_ALLOWED_HOSTS', 'localhost').split(',')



# =================================== Application definition ===================================
INSTALLED_APPS = [
    'modeltranslation',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',

    'assistant',
    'setting',
    'rest_framework',
    'channels',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',

    'django.middleware.locale.LocaleMiddleware',
    'setting.middleware.LanguageHeaderMiddleware',

    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',

]

ROOT_URLCONF = 'culture_chatbot.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.i18n',
            ],
        },
    },
]
# =================================== channels 설정 ===================================
ASGI_APPLICATION = "culture_chatbot.asgi.application"

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer",
    },
}


# =================================== csrf토큰 설정 ===================================
CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOWED_ORIGINS = [
    "https://sgimagine.com",  # 허용할 도메인
    "https://www.sgimagine.com",
    "http://localhost:8000",    # 로컬 개발 중일 때 허용
    "http://45.77.15.145",     # 서버의 IP 주소
]

CSRF_TRUSTED_ORIGINS = [
    "https://sgimagine.com",
    "https://www.sgimagine.com",
    "http://45.77.15.145",
]

# CORS 요청 허용 메서드 추가 (모바일 및 외부 요청 대응)
CORS_ALLOW_METHODS = [
    "GET",
    "POST",
    "PUT",
    "DELETE",
    "OPTIONS"
]

# 허용할 요청 헤더 추가
CORS_ALLOW_HEADERS = [
    "content-type",
    "x-csrftoken",
    "authorization",
    "accept"
]

# 세션 기반 인증 허용 (로그인 인증 관련)
CORS_ALLOW_CREDENTIALS = True

# =================================== wsgi ===================================
WSGI_APPLICATION = 'culture_chatbot.wsgi.application'


# =================================== Database ===================================
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST'),
        'PORT': config('DB_PORT'),
    }
}

# =================================== Password validation ===================================
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# =================================== Internationalization ===================================
# https://docs.djangoproject.com/en/5.1/topics/i18n/
USE_I18N = True

LANGUAGE_CODE = 'ko'
# 기본 언어
MODELTRANSLATION_DEFAULT_LANGUAGE = 'ko'

TIME_ZONE = 'Asia/Seoul'

USE_L10N = True

USE_TZ = True

SECURE_CROSS_ORIGIN_OPENER_POLICY = None


# =================================== Static files (CSS, JavaScript, Images) ===================================
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),  # static 디렉터리 설정
]

# 정적파일을 한곳에 
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# 미디어 파일 설정
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# =================================== locale 디렉토리 경로 설정 > 다국어 기능 ===================================
# 활성화 언어 목록
LANGUAGES = (
    ('ko', 'Korean'),
    ('en', 'English'),
    ('ja', 'Japanese'),
    ('fr', 'French'),
    ('de', 'German'),
)



# locale 디렉토리 경로 설정
LOCALE_PATHS = [ BASE_DIR / 'locale' ]



# =================================== Default primary key field type ===================================
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': 'redis://127.0.0.1:6379/1',
    }
}
