# Generated by Django 4.2.16 on 2025-06-30 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('priority', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CityCountyTown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='assistant.province')),
            ],
        ),
        migrations.CreateModel(
            name='Assistant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('photo', models.ImageField(default='assistant_photos/default.png', upload_to='assistant_photos/')),
                ('assistant_id', models.CharField(default='default_assistant_id', max_length=255, unique=True)),
                ('document_id', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(default='대한민국', max_length=100)),
                ('description', models.TextField(default='No description available')),
                ('prompt_context', models.TextField(blank=True, help_text='이 Assistant가 따르는 기본 프롬프트를 적어주세요 (말투/성격/역할 등)', null=True)),
                ('voice', models.CharField(choices=[('nova', 'Nova'), ('shimmer', 'Shimmer'), ('echo', 'Echo'), ('onyx', 'Onyx'), ('fable', 'Fable')], default='nova', help_text='TTS 음성 선택 (OpenAI에서 지원하는 음성 이름)', max_length=50)),
                ('welcome_message', models.TextField(default='환영합니다! 무엇을 도와드릴까요?')),
                ('question_1', models.CharField(blank=True, max_length=255, null=True)),
                ('question_2', models.CharField(blank=True, max_length=255, null=True)),
                ('question_3', models.CharField(blank=True, max_length=255, null=True)),
                ('question_4', models.CharField(blank=True, max_length=255, null=True)),
                ('question_5', models.CharField(blank=True, max_length=255, null=True)),
                ('question_6', models.CharField(blank=True, max_length=255, null=True)),
                ('question_7', models.CharField(blank=True, max_length=255, null=True)),
                ('question_8', models.CharField(blank=True, max_length=255, null=True)),
                ('question_9', models.CharField(blank=True, max_length=255, null=True)),
                ('question_10', models.CharField(blank=True, max_length=255, null=True)),
                ('city_county_town', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assistant.citycountytown')),
                ('province', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='assistant.province')),
                ('tags', models.ManyToManyField(blank=True, related_name='assistants', to='assistant.tag')),
            ],
        ),
    ]
