name: Deploy Django Application

on:
  push:
    branches:
      - main  # main 브랜치에 push될 때마다 실행

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # 최신 Ubuntu 서버에서 실행

    steps:
      # 1. 리포지토리에서 최신 코드 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v3  # Node 버전에 맞춰 최신 버전 사용

      # 2. Python 환경 설정
      - name: Set up Python
        uses: actions/setup-python@v4  # Node 버전에 맞춰 최신 버전 사용
        with:
          python-version: '3.8'

      # 3. 프로젝트의 의존성 설치
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Vultr 서버에 SSH로 접속해 배포 작업 수행
      - name: SSH and deploy to Vultr
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VULTR_SERVER_IP }}  # 서버 IP
          username: ${{ secrets.VULTR_USERNAME }}  # 사용자명 (예: linuxuser)
          key: ${{ secrets.VULTR_SSH_KEY }}  # SSH Private Key
          script: |
            cd /home/linuxuser/culture_chatbot  # 프로젝트 디렉토리로 이동
            git pull origin main  # GitHub에서 최신 코드 가져오기
            source venv/bin/activate  # 가상환경 활성화
            pip install -r requirements.txt  # 패키지 설치
            python manage.py migrate  # 마이그레이션
            python manage.py collectstatic --noinput  # 정적 파일 수집
            sudo systemctl restart gunicorn  # Gunicorn 재시작
            sudo systemctl restart nginx  # Nginx 재시작
